const SHAPE = "SHAPE"
const RECTANGLE = "RECTANGLE"
const CIRCLE = "CIRCLE"
const LINE = "LINE"
const SELECT = "SELECT"
const FILL_COLOR = "FILL_COLOR"
const STROKE_COLOR = "STROKE_COLOR"

export  {SHAPE,RECTANGLE,CIRCLE,LINE,SELECT,FILL_COLOR,STROKE_COLOR}