const FREE_DRAW = "FREE_DRAW"
const RECTANGLE = "RECTANGLE"
const CIRCLE = "CIRCLE"
const LINE = "LINE"
const POLYGON = "POLYGON"
const SELECT = "SELECT"
const DRAW = "DRAW"
const FILL_COLOR = "FILL_COLOR"
const STROKE_COLOR = "STROKE_COLOR"

export  {FREE_DRAW,RECTANGLE,CIRCLE,LINE,POLYGON,SELECT,FILL_COLOR,STROKE_COLOR,DRAW}